"""Initial schema setup

Revision ID: f6b17df50e69
Revises: 
Create Date: 2026-07-15 17:49:37.105903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b17df50e69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_key', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('rule_description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_rules_rule_key'), ['rule_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=False),
    sa.Column('employer_name', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('employment_stability_months', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('loan_purpose', sa.String(length=255), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('monthly_debt_obligations', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('fairness_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('blind_recommendation', sa.String(length=50), nullable=False),
    sa.Column('is_fair', sa.Boolean(), nullable=False),
    sa.Column('fairness_status', sa.String(length=50), nullable=False),
    sa.Column('blind_scores_json', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fairness_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fairness_checks_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fairness_checks_id'), ['id'], unique=False)

    op.create_table('human_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_reviews_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('policy_citations', sa.JSON(), nullable=True),
    sa.Column('reasons_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_id'), ['id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('debt_to_income_ratio', sa.Float(), nullable=False),
    sa.Column('employment_stability_months', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('income_stability_rating', sa.Float(), nullable=False),
    sa.Column('documentation_quality_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_id'), ['id'], unique=False)

    op.create_table('validation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('name_match_score', sa.Float(), nullable=False),
    sa.Column('dob_match_score', sa.Float(), nullable=False),
    sa.Column('income_consistency_pass', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('is_unreadable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_reports_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_reports_id'), ['id'], unique=False)

    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_results_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_results_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_results_document_id'))

    op.drop_table('ocr_results')
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_reports_id'))
        batch_op.drop_index(batch_op.f('ix_validation_reports_application_id'))

    op.drop_table('validation_reports')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_id'))
        batch_op.drop_index(batch_op.f('ix_scores_application_id'))

    op.drop_table('scores')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_application_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_human_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_human_reviews_application_id'))

    op.drop_table('human_reviews')
    with op.batch_alter_table('fairness_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fairness_checks_id'))
        batch_op.drop_index(batch_op.f('ix_fairness_checks_application_id'))

    op.drop_table('fairness_checks')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_application_id'))

    op.drop_table('documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_application_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_id'))
        batch_op.drop_index(batch_op.f('ix_applications_applicant_id'))

    op.drop_table('applications')
    op.drop_table('applicants')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rules_rule_key'))
        batch_op.drop_index(batch_op.f('ix_policy_rules_id'))

    op.drop_table('policy_rules')
    # ### end Alembic commands ###
